modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/ClientTweaks/issues"

[[mods]]
modId="clienttweaks"
version="${file.jarVersion}"
displayName="Client Tweaks"
displayURL="https://blay09.net/mods/clienttweaks"
logoFile="clienttweaks-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
There, I fixed Minecraft for you. Various optional tweaks to improve Minecraft Quality of Life.
'''

[[dependencies.clienttweaks]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clienttweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clienttweaks]]
    modId="balm"
    mandatory=true
    versionRange="[1.7.0,)"
    ordering="NONE"
    side="BOTH"
